### ISSUE TITLE
What about teacher model acc？

### ISSUE THREAD

**Issue by jinweiisgreat** [kleinzcy/Cr-KD-NCD#2]
I am very interested in your articles and code, but I encountered some issues while training the teacher model. I set the training epochs for the teacher model to 100, but I noticed that the accuracy is only around 0.79. Is this a normal phenomenon?

**Comment by kleinzcy** [comment]
Thanks for your attention. We have provided the checkpoint of teacher models, so you can evaluate the corresponding model to check your reimplementation.
