### ISSUE TITLE
What is the CUDA version you use?

### ISSUE THREAD

**Issue by JiuqingDong** [kleinzcy/Cr-KD-NCD#4]
<img width="639" alt="image" src="https://github.com/kleinzcy/Cr-KD-NCD/assets/111500217/7981bd57-d4f6-4f32-ac21-36f2379a6bfb">

This is my cuda version and driver of GPU. But I find that in your env.yaml, it is cuda10.2.
https://github.com/kleinzcy/Cr-KD-NCD/blob/68dd86508f31052a20cb8d0190c593df8c021640/env.yaml#L67

Since I got some error, so I want to know what is your cuda version?

**Comment by kleinzcy** [comment]
You can uncommemt the pytorch version in the requirement file, and install the pytorch that compatible with your cuda version.
