### ISSUE TITLE
Subject: Inquiry about Novel Class Accuracy in Task-Agnostic and Task-Aware Protocols

### ISSUE THREAD

**Issue by JiuqingDong** [kleinzcy/Cr-KD-NCD#6]
Dear Authors,

I hope this messagefinds you well. I have a question regarding the relationship between the novel class accuracy in task-agnostic and task-aware evaluation protocols.

In my understanding, under the task-aware evaluation protocol, since the unlabelled samples are pre-distinguished (i.e., separated into known and unknown categories), the novel class accuracy in task-aware settings should generally be higher than that in task-agnostic settings. However, when experimenting with the CUB dataset, I observed that the novel class accuracy in the task-aware protocol is actually lower than that in the task-agnostic protocol.

Could you help clarify why this might be the case? Is there a definitive relationship between the novel class accuracy in task-agnostic and task-aware evaluation protocols?

Thank you in advance for your time and insights. I look forward to your response!

主题：询问任务无关和任务感知协议中的新类别准确度

亲爱的作者，

希望您能收到这条消息。我有一个关于任务无关和任务感知评估协议中的新类别准确度之间关系的问题。

据我了解，在任务感知评估协议下，由于未标记的样本是预先区分的（即分为已知和未知类别），因此任务感知设置中的新类别准确度通常应高于任务无关设置中的新类别准确度。但是，在使用 CUB 数据集进行实验时，我发现任务感知协议中的新类别准确度实际上低于任务无关协议中的新类别准确度。

您能帮助澄清为什么会这样吗？任务无关和任务感知评估协议中的新类别准确度之间是否存在明确的关系？

感谢您的时间和见解。期待您的回复！

![image](https://github.com/user-attachments/assets/0f0597fe-2a89-45c8-a8d7-9b528d7c2786)

**Comment by kleinzcy** [comment]
Hi,
1. In the given table, the second novel is the results on testset, while the first one is trainset. So they are not comparable.
2. The results are influenced by clustering and matching algorithms. On the same dataset, the task-aware protocol is usually better than task-agnostic protocol.

**Comment by JiuqingDong** [comment]
Thank you for your response! It helps me a lot. 
Have a nice day!
